development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:c0a89075c9fb3a63580fc8c0fe4b845b@crestfish.redistogo.com:9466/
  channel_prefix: message_production
